"""
Training data for the email-intent classifier.

Each entry is a (text, intent) pair.  The model learns to classify user
utterances into one of the intents listed in INTENT_LABELS.
"""
from __future__ import annotations

INTENT_LABELS = [
    "compose",
    "reply",
    "forward",
    "read_inbox",
    "search",
    "delete",
    "draft",
    "greet",
    "help",
    "unknown",
]

TRAINING_SAMPLES: list[tuple[str, str]] = [
    # ── compose ──────────────────────────────────────────────────────────
    ("write an email to John about the meeting tomorrow", "compose"),
    ("send a message to alice@example.com", "compose"),
    ("compose a new email", "compose"),
    ("write a professional email to my manager", "compose"),
    ("send an email to the team about project update", "compose"),
    ("draft an email to HR regarding leave", "compose"),
    ("write an email requesting a meeting", "compose"),
    ("send a thank you email to Sarah", "compose"),
    ("compose a mail to client about proposal", "compose"),
    ("write email to professor about assignment extension", "compose"),
    ("send a follow-up email to the recruiter", "compose"),
    ("write a cold outreach email to potential client", "compose"),
    ("email my boss about the quarterly report", "compose"),
    ("create an email for project deadline extension", "compose"),
    ("write mail to vendor asking for quotation", "compose"),
    ("I need to send an email", "compose"),
    ("help me write an email", "compose"),
    ("compose a message to my colleague", "compose"),
    ("write a formal email", "compose"),
    ("send email to support team", "compose"),
    # ── reply ─────────────────────────────────────────────────────────────
    ("reply to the latest email from John", "reply"),
    ("respond to the email from my manager", "reply"),
    ("write a reply to this email", "reply"),
    ("answer the email about project proposal", "reply"),
    ("reply to Alice's message", "reply"),
    ("send a response to the interview invitation", "reply"),
    ("respond to the client's query", "reply"),
    ("reply to HR email", "reply"),
    ("write a response to the meeting invitation", "reply"),
    ("answer the last email I received", "reply"),
    ("respond to this thread", "reply"),
    ("write back to the recruiter", "reply"),
    ("reply to the support ticket", "reply"),
    ("respond to John's email about the deadline", "reply"),
    ("send reply to the newsletter", "reply"),
    # ── forward ───────────────────────────────────────────────────────────
    ("forward this email to my manager", "forward"),
    ("forward the message to the team", "forward"),
    ("send this email to Alice", "forward"),
    ("forward the invoice to accounts", "forward"),
    ("pass this email along to HR", "forward"),
    ("forward the meeting invite to Bob", "forward"),
    ("re-send this to the client", "forward"),
    ("forward the report to director", "forward"),
    ("please forward this to the finance team", "forward"),
    ("can you forward this email to Sarah", "forward"),
    ("forward the email chain to my colleague", "forward"),
    ("forward last email to john@example.com", "forward"),
    ("share this email with the CTO", "forward"),
    ("transfer this message to my supervisor", "forward"),
    ("forward the mail from Alice to the team", "forward"),
    # ── read_inbox ────────────────────────────────────────────────────────
    ("read my inbox", "read_inbox"),
    ("show me my emails", "read_inbox"),
    ("what emails do I have", "read_inbox"),
    ("check my inbox", "read_inbox"),
    ("any new emails", "read_inbox"),
    ("read latest email", "read_inbox"),
    ("show unread messages", "read_inbox"),
    ("what's in my inbox", "read_inbox"),
    ("open my emails", "read_inbox"),
    ("display inbox", "read_inbox"),
    ("read the email from John", "read_inbox"),
    ("show me the email about the project", "read_inbox"),
    ("read today's emails", "read_inbox"),
    ("any messages from Alice", "read_inbox"),
    ("show me unread mails", "read_inbox"),
    # ── search ─────────────────────────────────────────────────────────────
    ("find emails from John", "search"),
    ("search for emails about the project", "search"),
    ("look for the email with invoice", "search"),
    ("find all emails from last week", "search"),
    ("search emails from alice@example.com", "search"),
    ("look up the meeting confirmation email", "search"),
    ("find the email about salary", "search"),
    ("search for messages with attachment", "search"),
    ("find emails containing contract", "search"),
    ("look for unread emails from manager", "search"),
    ("search inbox for proposal", "search"),
    ("find all emails from HR", "search"),
    # ── delete ─────────────────────────────────────────────────────────────
    ("delete this email", "delete"),
    ("trash the email from John", "delete"),
    ("remove the email about promotion", "delete"),
    ("delete all spam emails", "delete"),
    ("move this email to trash", "delete"),
    ("discard this message", "delete"),
    ("delete the newsletter emails", "delete"),
    ("remove unread emails", "delete"),
    # ── draft ─────────────────────────────────────────────────────────────
    ("save as draft", "draft"),
    ("save this email as draft", "draft"),
    ("keep it as a draft", "draft"),
    ("save draft", "draft"),
    ("don't send, just save", "draft"),
    ("store as draft and send later", "draft"),
    ("save for later", "draft"),
    # ── greet ─────────────────────────────────────────────────────────────
    ("hello", "greet"),
    ("hi", "greet"),
    ("hey", "greet"),
    ("good morning", "greet"),
    ("good afternoon", "greet"),
    ("good evening", "greet"),
    ("hi there", "greet"),
    ("hey assistant", "greet"),
    ("hello email assistant", "greet"),
    ("what's up", "greet"),
    # ── help ──────────────────────────────────────────────────────────────
    ("help", "help"),
    ("what can you do", "help"),
    ("show commands", "help"),
    ("what are your features", "help"),
    ("how do I use you", "help"),
    ("guide me", "help"),
    ("list commands", "help"),
    ("what can I ask", "help"),
    ("how does this work", "help"),
    ("I need help", "help"),
    ("show help", "help"),
    ("what are your capabilities", "help"),
    ("what commands do you support", "help"),
    ("what functions can you perform", "help"),
    ("tell me what you can do", "help"),
    ("assist me with email", "help"),
    ("how to use this assistant", "help"),
    # ── unknown ───────────────────────────────────────────────────────────
    ("what is the weather today", "unknown"),
    ("tell me a joke", "unknown"),
    ("calculate 2 plus 2", "unknown"),
    ("who is the president", "unknown"),
    ("play music", "unknown"),
    ("set a reminder", "unknown"),
    ("open browser", "unknown"),
    ("what time is it", "unknown"),
    ("news headlines today", "unknown"),
    ("translate this sentence to Spanish", "unknown"),
    ("turn off the lights", "unknown"),
    ("book a flight to New York", "unknown"),
    ("order pizza online", "unknown"),
]
